"""add_uuid_index

Revision ID: 6fcdb32e5991
Revises: 97654229837b
Create Date: 2026-02-21 20:38:26.121285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcdb32e5991'
down_revision: Union[str, Sequence[str], None] = '97654229837b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('books_uuid_key'), 'books', type_='unique')
    op.create_index(op.f('ix_books_uuid'), 'books', ['uuid'], unique=True)
    op.drop_constraint(op.f('users_uuid_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.create_unique_constraint(op.f('users_uuid_key'), 'users', ['uuid'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_books_uuid'), table_name='books')
    op.create_unique_constraint(op.f('books_uuid_key'), 'books', ['uuid'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
